package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/kenyamaneko/overload-party-gateway/internal/model"
	"github.com/kenyamaneko/overload-party-gateway/internal/port"
)

// Compile-time interface check.
var _ port.DeckRepo = (*PgDeckRepository)(nil)

// PgDeckRepository implements DeckRepo backed by PostgreSQL via pgxpool.
type PgDeckRepository struct {
	pool *pgxpool.Pool
}

// NewPgDeckRepository returns a new PgDeckRepository.
func NewPgDeckRepository(pool *pgxpool.Pool) *PgDeckRepository {
	return &PgDeckRepository{pool: pool}
}

// Create inserts a deck and its cards atomically.
// deck_id is generated by the database (GENERATED ALWAYS AS IDENTITY).
func (r *PgDeckRepository) Create(ctx context.Context, deck *model.Deck, cards []model.DeckCard) error {
	if txFromContext(ctx) != nil {
		return r.createInner(ctx, connFrom(ctx, r.pool), deck, cards)
	}
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := r.createInner(ctx, tx, deck, cards); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

func (r *PgDeckRepository) createInner(ctx context.Context, db dbtx, deck *model.Deck, cards []model.DeckCard) error {
	err := db.QueryRow(ctx,
		`INSERT INTO decks (player_id, deck_name, playmat_no, sleeve_no, created_at, updated_at)
		 VALUES ($1,$2,$3,$4,$5,$6) RETURNING deck_id`,
		deck.PlayerID,
		deck.DeckName,
		deck.PlaymatNo,
		deck.SleeveNo,
		deck.CreatedAt,
		deck.UpdatedAt,
	).Scan(&deck.DeckID)
	if err != nil {
		return fmt.Errorf("insert deck: %w", err)
	}

	for i := range cards {
		cards[i].DeckID = deck.DeckID
	}

	return bulkInsertDeckCards(ctx, db, cards)
}

// FindByPlayerID returns all decks for a player, ordered by updated_at descending.
func (r *PgDeckRepository) FindByPlayerID(ctx context.Context, playerID string) ([]*model.Deck, error) {
	rows, err := connFrom(ctx, r.pool).Query(ctx,
		`SELECT player_id, deck_id, deck_name, playmat_no, sleeve_no, created_at, updated_at
		 FROM decks WHERE player_id = $1 ORDER BY updated_at DESC`,
		playerID,
	)
	if err != nil {
		return nil, fmt.Errorf("query decks: %w", err)
	}
	defer rows.Close()

	decks := make([]*model.Deck, 0, 8)
	for rows.Next() {
		d, err := scanDeck(rows)
		if err != nil {
			return nil, fmt.Errorf("scan deck: %w", err)
		}
		decks = append(decks, d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate decks: %w", err)
	}
	return decks, nil
}

// FindByID returns a single deck by player_id and deck_id.
func (r *PgDeckRepository) FindByID(ctx context.Context, playerID string, deckID int64) (*model.Deck, error) {
	row := connFrom(ctx, r.pool).QueryRow(ctx,
		`SELECT player_id, deck_id, deck_name, playmat_no, sleeve_no, created_at, updated_at
		 FROM decks WHERE player_id = $1 AND deck_id = $2`,
		playerID, deckID,
	)

	d, err := scanDeck(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("deck %d for player %s: %w", deckID, playerID, port.ErrNotFound)
		}
		return nil, fmt.Errorf("find deck by id: %w", err)
	}
	return d, nil
}

// GetDeckCards returns the deck_cards rows for a given deck.
func (r *PgDeckRepository) GetDeckCards(ctx context.Context, playerID string, deckID int64) ([]model.DeckCard, error) {
	rows, err := connFrom(ctx, r.pool).Query(ctx,
		`SELECT player_id, deck_id, card_id, art_no, count
		 FROM deck_cards WHERE player_id = $1 AND deck_id = $2`,
		playerID, deckID,
	)
	if err != nil {
		return nil, fmt.Errorf("query deck cards: %w", err)
	}
	defer rows.Close()

	cards := make([]model.DeckCard, 0, 16)
	for rows.Next() {
		var dc model.DeckCard
		if err := rows.Scan(&dc.PlayerID, &dc.DeckID, &dc.CardID, &dc.ArtNo, &dc.Count); err != nil {
			return nil, fmt.Errorf("scan deck card: %w", err)
		}
		cards = append(cards, dc)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate deck cards: %w", err)
	}
	return cards, nil
}

// Update replaces a deck's metadata and cards atomically.
func (r *PgDeckRepository) Update(ctx context.Context, deck *model.Deck, cards []model.DeckCard) error {
	if txFromContext(ctx) != nil {
		return r.updateInner(ctx, connFrom(ctx, r.pool), deck, cards)
	}
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := r.updateInner(ctx, tx, deck, cards); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

func (r *PgDeckRepository) updateInner(ctx context.Context, db dbtx, deck *model.Deck, cards []model.DeckCard) error {
	_, err := db.Exec(ctx,
		`DELETE FROM deck_cards WHERE player_id = $1 AND deck_id = $2`,
		deck.PlayerID, deck.DeckID,
	)
	if err != nil {
		return fmt.Errorf("delete old deck cards: %w", err)
	}

	now := time.Now()
	deck.UpdatedAt = now
	_, err = db.Exec(ctx,
		`UPDATE decks SET deck_name = $1, playmat_no = $2, sleeve_no = $3, updated_at = $4
		 WHERE player_id = $5 AND deck_id = $6`,
		deck.DeckName,
		deck.PlaymatNo,
		deck.SleeveNo,
		deck.UpdatedAt,
		deck.PlayerID,
		deck.DeckID,
	)
	if err != nil {
		return fmt.Errorf("update deck: %w", err)
	}

	return bulkInsertDeckCards(ctx, db, cards)
}

// Delete removes a deck by primary key. CASCADE on the foreign key handles deck_cards.
func (r *PgDeckRepository) Delete(ctx context.Context, playerID string, deckID int64) error {
	_, err := connFrom(ctx, r.pool).Exec(ctx,
		`DELETE FROM decks WHERE player_id = $1 AND deck_id = $2`,
		playerID, deckID,
	)
	if err != nil {
		return fmt.Errorf("delete deck: %w", err)
	}
	return nil
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// scanDeck scans a single row into a model.Deck.
func scanDeck(row pgx.Row) (*model.Deck, error) {
	var d model.Deck
	err := row.Scan(
		&d.PlayerID,
		&d.DeckID,
		&d.DeckName,
		&d.PlaymatNo,
		&d.SleeveNo,
		&d.CreatedAt,
		&d.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &d, nil
}

// bulkInsertDeckCards inserts multiple deck_cards rows in a single INSERT statement.
func bulkInsertDeckCards(ctx context.Context, db dbtx, cards []model.DeckCard) error {
	if len(cards) == 0 {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("INSERT INTO deck_cards (player_id, deck_id, card_id, art_no, count) VALUES ")

	args := make([]interface{}, 0, len(cards)*5)
	for i, c := range cards {
		if i > 0 {
			sb.WriteString(",")
		}
		base := i*5 + 1
		fmt.Fprintf(&sb, "($%d,$%d,$%d,$%d,$%d)", base, base+1, base+2, base+3, base+4)
		args = append(args, c.PlayerID, c.DeckID, c.CardID, c.ArtNo, c.Count)
	}

	_, err := db.Exec(ctx, sb.String(), args...)
	if err != nil {
		return fmt.Errorf("insert deck cards: %w", err)
	}
	return nil
}
