// Code generated by scripts/generate_types.py; DO NOT EDIT.

export const WS_SERVER_MSG_TYPES = ["game_state", "game_over", "error", "game_entered", "matchmaking_started", "matchmaking_cancelled", "action_rejected", "stamp_used", "pong", "match_found", "action_performed", "turn_controls", "npc_battle_created", "opponent_disconnected", "opponent_reconnected", "spectate_joined", "spectate_error", "spectate_update", "spectate_ended", "spectate_stamp_broadcast", "game_state_restore"] as const;
export type WSServerMsgType = (typeof WS_SERVER_MSG_TYPES)[number];

export const WS_CLIENT_MSG_TYPES = ["game_enter", "matchmaking_start", "matchmaking_cancel", "game_action", "use_stamp", "ping", "npc_battle_start", "spectate_join", "spectate_leave", "spectate_stamp"] as const;
export type WSClientMsgType = (typeof WS_CLIENT_MSG_TYPES)[number];

