// Code generated by asyncapi-codegen-tools from asyncapi.yaml; DO NOT EDIT.

package apigateway

// GameEnterMessage は 既存ゲームへ参加する要求 (PvP マッチ成立後の入室など)。
type GameEnterMessage struct {
	GameID string `json:"game_id"`
	DeckID int64  `json:"deck_id"`
}

// MatchmakingStartMessage は マッチング待ち行列への登録要求。
type MatchmakingStartMessage struct {
	DeckID int64 `json:"deck_id"`
}

// GameActionMessage は プレイヤーが実行したアクションをサーバーへ送信する。
type GameActionMessage struct {
	GameID     string                 `json:"game_id"`
	ActionType string                 `json:"action_type"`
	Data       map[string]interface{} `json:"data"`
}

// UseStampMessage は 対戦中のスタンプ送信。
type UseStampMessage struct {
	GameID  string `json:"game_id"`
	StampNo int64  `json:"stamp_no"`
}

// NpcBattleStartMessage は NPC バトル開始要求。
type NpcBattleStartMessage struct {
	DeckID   int64  `json:"deck_id"`
	NpcModel string `json:"npc_model"`
}

// SpectateJoinMessage は 観戦対象のゲームへ参加する要求。
type SpectateJoinMessage struct {
	GameID string `json:"game_id"`
}

// SpectateLeaveMessage は 観戦から離脱する要求。
type SpectateLeaveMessage struct {
	GameID string `json:"game_id"`
}

// SpectateStampMessage は 観戦中のスタンプ送信。
type SpectateStampMessage struct {
	GameID  string `json:"game_id"`
	StampNo int64  `json:"stamp_no"`
}

// ErrorMessage は サーバー由来のエラー通知。
type ErrorMessage struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

// MatchFoundMessage は マッチング成立通知。
type MatchFoundMessage struct {
	GameID string `json:"game_id"`
}

// GameOverMessage は ゲーム終了通知。
type GameOverMessage struct {
	GameID           string `json:"game_id"`
	WinningPlayerNum int64  `json:"winning_player_num"`
	WinReason        string `json:"win_reason"`
}

// ActionRejectedMessage は アクション拒否通知。
type ActionRejectedMessage struct {
	GameID     string `json:"game_id"`
	ActionType string `json:"action_type"`
	Reason     string `json:"reason"`
}

// ActionPerformedMessage は アクション実行とその後の (情報秘匿適用済み) ゲーム状態通知。
type ActionPerformedMessage struct {
	Sequence   int64                  `json:"sequence"`
	ActionType string                 `json:"action_type"`
	ActionData map[string]interface{} `json:"action_data"`
	State      map[string]interface{} `json:"state"`
}

// StampUsedMessage は 対戦相手 (または自分) のスタンプ送信通知。
type StampUsedMessage struct {
	GameID    string `json:"game_id"`
	PlayerNum int64  `json:"player_num"`
	StampNo   int64  `json:"stamp_no"`
}

// NpcBattleCreatedMessage は NPC バトル作成完了通知。
type NpcBattleCreatedMessage struct {
	GameID string `json:"game_id"`
}

// OpponentDisconnectedMessage は 対戦相手の切断通知 (空ペイロード)。
type OpponentDisconnectedMessage struct {
}

// OpponentReconnectedMessage は 対戦相手の再接続通知 (空ペイロード)。
type OpponentReconnectedMessage struct {
}

// SpectateJoinedMessage は 観戦参加成立 + 初期状態通知。
type SpectateJoinedMessage struct {
	GameID       string                 `json:"game_id"`
	Player1Name  string                 `json:"player1_name"`
	Player1Level int64                  `json:"player1_level"`
	Player2Name  string                 `json:"player2_name"`
	Player2Level int64                  `json:"player2_level"`
	State        map[string]interface{} `json:"state"`
}

// SpectateErrorMessage は 観戦処理におけるエラー通知。
type SpectateErrorMessage struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

// SpectateEndedMessage は 観戦対象のゲーム終了通知。
type SpectateEndedMessage struct {
	GameID           string `json:"game_id"`
	WinningPlayerNum int64  `json:"winning_player_num"`
	WinReason        string `json:"win_reason"`
}

// SpectateStampBroadcastMessage は 観戦者からのスタンプ broadcast 通知。
type SpectateStampBroadcastMessage struct {
	GameID      string `json:"game_id"`
	SpectatorID string `json:"spectator_id"`
	StampNo     int64  `json:"stamp_no"`
}

