// Code generated by asyncapi-codegen-tools from asyncapi.yaml; DO NOT EDIT.

package apigateway

import (
	"encoding/json"
)

// GameEnterMessage は 既存ゲームへ参加する要求 (PvP マッチ成立後の入室など)。
type GameEnterMessage struct {
	GameID string `json:"game_id"`
	DeckID int64  `json:"deck_id"`
}

// MatchmakingStartMessage は マッチング待ち行列への登録要求。
type MatchmakingStartMessage struct {
	DeckID int64 `json:"deck_id"`
}

// GameActionMessage は プレイヤーが実行したアクションをサーバーへ送信する。
type GameActionMessage struct {
	GameID     string                 `json:"game_id"`
	ActionType string                 `json:"action_type"`
	Data       json.RawMessage       `json:"data"`
}

// UseStampMessage は 対戦中のスタンプ送信。
type UseStampMessage struct {
	GameID  string `json:"game_id"`
	StampNo int64  `json:"stamp_no"`
}

// NpcBattleStartMessage は NPC バトル開始要求。
type NpcBattleStartMessage struct {
	DeckID   int64  `json:"deck_id"`
	NpcModel string `json:"npc_model"`
}

// ErrorMessage は サーバー由来のエラー通知。
type ErrorMessage struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

// MatchFoundMessage は マッチング成立通知。
type MatchFoundMessage struct {
	GameID string `json:"game_id"`
}

// GameOverMessage は ゲーム終了通知。
type GameOverMessage struct {
	GameID           string `json:"game_id"`
	WinningPlayerNum int64  `json:"winning_player_num"`
	WinReason        string `json:"win_reason"`
}

// ActionRejectedMessage は アクション拒否通知。
type ActionRejectedMessage struct {
	GameID     string `json:"game_id"`
	ActionType string `json:"action_type"`
	Reason     string `json:"reason"`
}

// ActionPerformedMessage は アクション実行とその後の (情報秘匿適用済み) ゲーム状態通知。
type ActionPerformedMessage struct {
	Sequence   int64                  `json:"sequence"`
	ActionType string                 `json:"action_type"`
	ActionData json.RawMessage       `json:"action_data"`
	State      json.RawMessage       `json:"state"`
}

// StampUsedMessage は 対戦相手 (または自分) のスタンプ送信通知。
type StampUsedMessage struct {
	GameID    string `json:"game_id"`
	PlayerNum int64  `json:"player_num"`
	StampNo   int64  `json:"stamp_no"`
}

// NpcBattleCreatedMessage は NPC バトル作成完了通知。
type NpcBattleCreatedMessage struct {
	GameID string `json:"game_id"`
}

// OpponentDisconnectedMessage は 対戦相手の切断通知 (空ペイロード)。
type OpponentDisconnectedMessage struct {
}

// OpponentReconnectedMessage は 対戦相手の再接続通知 (空ペイロード)。
type OpponentReconnectedMessage struct {
}

// ServerUpdateMessage は サーバー更新による接続終了の通知 (空ペイロード)。
type ServerUpdateMessage struct {
}

