// Package apigateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apigateway

import (
	"time"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// PlayerResponse defines model for PlayerResponse.
type PlayerResponse struct {
	CreatedAt      time.Time `json:"created_at"`
	EquippedIconNo *int64    `json:"equipped_icon_no,omitempty"`
	Exp            int64     `json:"exp"`
	FirebaseUID    string    `json:"firebase_uid"`
	IsPremium      bool      `json:"is_premium"`
	Level          int64     `json:"level"`

	// LevelExpCurrent 現在レベル内の経験値
	LevelExpCurrent int64 `json:"level_exp_current"`

	// LevelExpRequired 次レベルまでの必要経験値
	LevelExpRequired int64 `json:"level_exp_required"`

	// Name プレイヤー名 (オンボーディング未完了時は null)
	Name             *string    `json:"name,omitempty"`
	PlayerID         string     `json:"player_id"`
	PremiumExpiresAt *time.Time `json:"premium_expires_at,omitempty"`
	SelectedFaction  *string    `json:"selected_faction,omitempty"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// ForceUpdate true の場合、クライアントはストアへ誘導する
	ForceUpdate bool `json:"forceUpdate"`

	// LatestVersion 最新バージョン
	LatestVersion string `json:"latestVersion"`

	// MinimumVersion 最低要求バージョン
	MinimumVersion string `json:"minimumVersion"`

	// StoreURL ストア URL
	StoreURL string `json:"storeUrl"`
}
