// Package apigateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apigateway

import (
	"time"
)

// Defines values for AnnouncementType.
const (
	AnnouncementTypeInfo        AnnouncementType = "info"
	AnnouncementTypeMaintenance AnnouncementType = "maintenance"
	AnnouncementTypeWarning     AnnouncementType = "warning"
)

// Valid indicates whether the value is a known member of the AnnouncementType enum.
func (e AnnouncementType) Valid() bool {
	switch e {
	case AnnouncementTypeInfo:
		return true
	case AnnouncementTypeMaintenance:
		return true
	case AnnouncementTypeWarning:
		return true
	default:
		return false
	}
}

// Announcement defines model for Announcement.
type Announcement struct {
	Body      string     `json:"body"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// ID お知らせID
	ID          string    `json:"id"`
	PublishedAt time.Time `json:"published_at"`
	Title       string    `json:"title"`

	// Type お知らせの種別
	Type AnnouncementType `json:"type"`
}

// AnnouncementType お知らせの種別
type AnnouncementType string

// BattleLimitResponse defines model for BattleLimitResponse.
type BattleLimitResponse struct {
	CanBattle        bool  `json:"can_battle"`
	DailyBattleCount int64 `json:"daily_battle_count"`

	// DailyBattleLimit -1 で無制限 (プレミアム会員)
	DailyBattleLimit int64 `json:"daily_battle_limit"`
}

// DailyTip defines model for DailyTip.
type DailyTip struct {
	// ID TipID
	ID   string `json:"id"`
	Text string `json:"text"`
}

// Deck defines model for Deck.
type Deck struct {
	CreatedAt time.Time   `json:"created_at"`
	DeckCards *[]DeckCard `json:"deck_cards,omitempty"`
	DeckID    int64       `json:"deck_id"`
	DeckName  string      `json:"deck_name"`

	// IsValid バトル使用可能か (都度算出: 30 枚 + 全カード所持 + 制限枚数以内)
	IsValid   bool      `json:"is_valid"`
	PlayerID  string    `json:"player_id"`
	PlaymatNo *int64    `json:"playmat_no,omitempty"`
	SleeveNo  *int64    `json:"sleeve_no,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// DeckCard defines model for DeckCard.
type DeckCard struct {
	ArtNo    int64  `json:"art_no"`
	CardID   string `json:"card_id"`
	Count    int32  `json:"count"`
	DeckID   int64  `json:"deck_id"`
	PlayerID string `json:"player_id"`
}

// DeckCardEntry defines model for DeckCardEntry.
type DeckCardEntry struct {
	ArtNo  int64  `json:"art_no"`
	CardID string `json:"card_id"`
	Count  int32  `json:"count"`
}

// DeckCreateRequest defines model for DeckCreateRequest.
type DeckCreateRequest struct {
	Cards     []DeckCardEntry `json:"cards"`
	DeckName  string          `json:"deck_name"`
	PlaymatNo *int64          `json:"playmat_no,omitempty"`
	SleeveNo  *int64          `json:"sleeve_no,omitempty"`
}

// DeckDetailResponse defines model for DeckDetailResponse.
type DeckDetailResponse struct {
	Cards []DeckCard `json:"cards"`
	Deck  Deck       `json:"deck"`
}

// DeckUpdateRequest defines model for DeckUpdateRequest.
type DeckUpdateRequest struct {
	Cards     []DeckCardEntry `json:"cards"`
	DeckName  string          `json:"deck_name"`
	PlaymatNo *int64          `json:"playmat_no,omitempty"`
	SleeveNo  *int64          `json:"sleeve_no,omitempty"`
}

// EpisodeListResponse defines model for EpisodeListResponse.
type EpisodeListResponse struct {
	Episodes []EpisodeWithStatus `json:"episodes"`
}

// EpisodeWithStatus defines model for EpisodeWithStatus.
type EpisodeWithStatus struct {
	EpisodeID     string       `json:"episode_id"`
	EpisodeNumber int64        `json:"episode_number"`
	Faction       *string      `json:"faction,omitempty"`
	IsCompleted   bool         `json:"is_completed"`
	IsUnlocked    bool         `json:"is_unlocked"`
	LockReasons   []LockReason `json:"lock_reasons"`
	ThumbnailURL  *string      `json:"thumbnail_url,omitempty"`
	Title         string       `json:"title"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LockReason defines model for LockReason.
type LockReason struct {
	// Current 現在値 (level の場合のみ)
	Current interface{} `json:"current,omitempty"`

	// Required 必要値 (種別により型が異なる)
	Required interface{} `json:"required"`

	// Type 条件種別 (`level` / `faction` / `episode`)
	Type string `json:"type"`
}

// NewsArticle defines model for NewsArticle.
type NewsArticle struct {
	ArticleID   string     `json:"article_id"`
	FetchedAt   time.Time  `json:"fetched_at"`
	PublishedAt *time.Time `json:"published_at,omitempty"`

	// Source ソース (`aws` / `google-cloud` / `azure` / `oci` / `other`)
	Source string `json:"source"`

	// Summary AI 要約 (未完了の場合 null)
	Summary *string  `json:"summary,omitempty"`
	Tags    []string `json:"tags"`
	Title   string   `json:"title"`
}

// NpcModel defines model for NpcModel.
type NpcModel struct {
	// Difficulty 難易度 (`easy` / `hard`)
	Difficulty  string `json:"difficulty"`
	DisplayName string `json:"display_name"`
	Faction     string `json:"faction"`
	Model       string `json:"model"`
}

// OnboardingCompleteRequest defines model for OnboardingCompleteRequest.
type OnboardingCompleteRequest struct {
	// InitialFactionID 初期 faction (`SHE` / `Tenki` / `Sugar` / `Tuners`)
	InitialFactionID string `json:"initial_faction_id"`
}

// OnboardingCompleteResponse defines model for OnboardingCompleteResponse.
type OnboardingCompleteResponse struct {
	Message  string `json:"message"`
	PlayerID string `json:"player_id"`
}

// OnboardingNameRequest defines model for OnboardingNameRequest.
type OnboardingNameRequest struct {
	Name string `json:"name"`
}

// OnboardingResumeResponse defines model for OnboardingResumeResponse.
type OnboardingResumeResponse struct {
	// NextCheckpoint 次の checkpoint (`started` / `name_set` / `faction_set` / `completed`)
	NextCheckpoint string `json:"next_checkpoint"`
	PlayerID       string `json:"player_id"`
}

// OnboardingScriptResponse defines model for OnboardingScriptResponse.
type OnboardingScriptResponse struct {
	Script string `json:"script"`
}

// OnboardingStatus defines model for OnboardingStatus.
type OnboardingStatus struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	Onboarded   bool       `json:"onboarded"`
	PlayerID    string     `json:"player_id"`
}

// PlayerCardWithDef defines model for PlayerCardWithDef.
type PlayerCardWithDef struct {
	ArtNo       int64   `json:"art_no"`
	CardID      string  `json:"card_id"`
	CardName    string  `json:"card_name"`
	CardType    string  `json:"card_type"`
	Count       int32   `json:"count"`
	DeployTurns int64   `json:"deploy_turns"`
	EffectText  *string `json:"effect_text,omitempty"`
	Elastic     bool    `json:"elastic"`
	Faction     string  `json:"faction"`
	Resizable   bool    `json:"resizable"`

	// ResourceLabel リソースラベル (AWS/Azure/Google Cloud/Oracle 等のサービス名)
	ResourceLabel string `json:"resource_label"`

	// Restriction 制限 (`unlimited` / `semi_limited` / `limited` / `forbidden`)
	Restriction string `json:"restriction"`

	// Stats ComputeStats または DataStats (downstream の型をそのまま中継)
	Stats map[string]interface{} `json:"stats"`
}

// PlayerNameRequest defines model for PlayerNameRequest.
type PlayerNameRequest struct {
	Name string `json:"name"`
}

// PlayerResponse defines model for PlayerResponse.
type PlayerResponse struct {
	CreatedAt      time.Time `json:"created_at"`
	EquippedIconNo *int64    `json:"equipped_icon_no,omitempty"`
	Exp            int64     `json:"exp"`
	FirebaseUID    string    `json:"firebase_uid"`
	IsPremium      bool      `json:"is_premium"`
	Level          int64     `json:"level"`

	// LevelExpCurrent 現在レベル内の経験値
	LevelExpCurrent int64 `json:"level_exp_current"`

	// LevelExpRequired 次レベルまでの必要経験値
	LevelExpRequired int64 `json:"level_exp_required"`

	// Name プレイヤー名 (オンボーディング未完了時は null)
	Name             *string    `json:"name,omitempty"`
	PlayerID         string     `json:"player_id"`
	PremiumExpiresAt *time.Time `json:"premium_expires_at,omitempty"`
	SelectedFaction  *string    `json:"selected_faction,omitempty"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// PlayerSettings defines model for PlayerSettings.
type PlayerSettings struct {
	BgmVolume int64 `json:"bgm_volume"`

	// Language 言語 (`ja` / `en`)
	Language    string    `json:"language"`
	PlayerID    string    `json:"player_id"`
	PushEnabled bool      `json:"push_enabled"`
	SeVolume    int64     `json:"se_volume"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Products []ProductResponse `json:"products"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	// Content 商品内容 (種別により構造が異なる、shop の生 JSON を中継)
	Content     map[string]interface{} `json:"content"`
	Description *string                `json:"description,omitempty"`
	ImageURL    *string                `json:"image_url,omitempty"`
	IsActive    bool                   `json:"is_active"`
	IsOwned     bool                   `json:"is_owned"`
	Name        string                 `json:"name"`
	Price       int64                  `json:"price"`
	ProductID   string                 `json:"product_id"`

	// Type 商品種別 (downstream shop の ProductType と一致)
	Type string `json:"type"`
}

// PurchaseRequest defines model for PurchaseRequest.
type PurchaseRequest struct {
	// Platform プラットフォーム (`ios` / `android`)
	Platform      string `json:"platform"`
	ProductID     string `json:"product_id"`
	PurchaseToken string `json:"purchase_token"`
}

// PurchaseResponse defines model for PurchaseResponse.
type PurchaseResponse struct {
	Message   string `json:"message"`
	ProductID string `json:"product_id"`
}

// ScenarioCompleteResponse defines model for ScenarioCompleteResponse.
type ScenarioCompleteResponse struct {
	EpisodeID string `json:"episode_id"`
	Message   string `json:"message"`
}

// ScenarioScriptResponse defines model for ScenarioScriptResponse.
type ScenarioScriptResponse struct {
	EpisodeID string `json:"episode_id"`
	Script    string `json:"script"`
}

// SelectFactionRequest defines model for SelectFactionRequest.
type SelectFactionRequest struct {
	// Faction ファクション (`SHE` / `Tenki` / `Sugar` / `Tuners`)
	Faction string `json:"faction"`
}

// SelectFactionResponse defines model for SelectFactionResponse.
type SelectFactionResponse struct {
	CardsGranted int64  `json:"cards_granted"`
	Faction      string `json:"faction"`
	Message      string `json:"message"`
}

// SpectateGameInfo defines model for SpectateGameInfo.
type SpectateGameInfo struct {
	GameID    string    `json:"game_id"`
	Player1ID string    `json:"player1_id"`
	Player2ID string    `json:"player2_id"`
	StartedAt time.Time `json:"started_at"`
}

// SubscribeResponse defines model for SubscribeResponse.
type SubscribeResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	Message   string    `json:"message"`
}

// UpdateSettingsRequest 部分更新。指定フィールドのみ更新される。
type UpdateSettingsRequest struct {
	BgmVolume   *int64  `json:"bgm_volume,omitempty"`
	Language    *string `json:"language,omitempty"`
	PushEnabled *bool   `json:"push_enabled,omitempty"`
	SeVolume    *int64  `json:"se_volume,omitempty"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// ForceUpdate true の場合、クライアントはストアへ誘導する
	ForceUpdate bool `json:"forceUpdate"`

	// LatestVersion 最新バージョン
	LatestVersion string `json:"latestVersion"`

	// MinimumVersion 最低要求バージョン
	MinimumVersion string `json:"minimumVersion"`

	// StoreURL ストア URL
	StoreURL string `json:"storeUrl"`
}

// DeckIdPath defines model for DeckIdPath.
type DeckIdPath = int64

// EpisodeIdPath defines model for EpisodeIdPath.
type EpisodeIdPath = string

// GameIdPath defines model for GameIdPath.
type GameIdPath = string

// ListCloudNewsParams defines parameters for ListCloudNews.
type ListCloudNewsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetOnboardingScriptParams defines parameters for GetOnboardingScript.
type GetOnboardingScriptParams struct {
	Lang *string `form:"lang,omitempty" json:"lang,omitempty"`
}

// ListScenariosParams defines parameters for ListScenarios.
type ListScenariosParams struct {
	Lang *string `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetScenarioScriptParams defines parameters for GetScenarioScript.
type GetScenarioScriptParams struct {
	Lang *string `form:"lang,omitempty" json:"lang,omitempty"`
}

// CompleteOnboardingJSONRequestBody defines body for CompleteOnboarding for application/json ContentType.
type CompleteOnboardingJSONRequestBody = OnboardingCompleteRequest

// SetOnboardingNameJSONRequestBody defines body for SetOnboardingName for application/json ContentType.
type SetOnboardingNameJSONRequestBody = OnboardingNameRequest

// CreateDeckJSONRequestBody defines body for CreateDeck for application/json ContentType.
type CreateDeckJSONRequestBody = DeckCreateRequest

// UpdateDeckJSONRequestBody defines body for UpdateDeck for application/json ContentType.
type UpdateDeckJSONRequestBody = DeckUpdateRequest

// UpdatePlayerNameJSONRequestBody defines body for UpdatePlayerName for application/json ContentType.
type UpdatePlayerNameJSONRequestBody = PlayerNameRequest

// SelectFactionJSONRequestBody defines body for SelectFaction for application/json ContentType.
type SelectFactionJSONRequestBody = SelectFactionRequest

// UpdatePlayerSettingsJSONRequestBody defines body for UpdatePlayerSettings for application/json ContentType.
type UpdatePlayerSettingsJSONRequestBody = UpdateSettingsRequest

// PurchaseProductJSONRequestBody defines body for PurchaseProduct for application/json ContentType.
type PurchaseProductJSONRequestBody = PurchaseRequest

// SubscribeProductJSONRequestBody defines body for SubscribeProduct for application/json ContentType.
type SubscribeProductJSONRequestBody = PurchaseRequest
