// Code generated by generate_from_yaml.py from data/models.yaml; DO NOT EDIT.

package model

import (
	"time"

	"cloud.google.com/go/civil"
)

type Player struct {
	PlayerID         string     `json:"player_id" db:"player_id"`
	FirebaseUID      string     `json:"firebase_uid" db:"firebase_uid"`
	Username         string     `json:"username" db:"username"`
	Level            int64      `json:"level" db:"level"`
	Exp              int64      `json:"exp" db:"exp"`
	Wins             int64      `json:"wins" db:"wins"`
	Losses           int64      `json:"losses" db:"losses"`
	IsPremium        bool       `json:"is_premium" db:"is_premium"`
	EquippedIconNo   *int64     `json:"equipped_icon_no,omitempty" db:"equipped_icon_no"`
	SelectedFaction  *string    `json:"selected_faction,omitempty" db:"selected_faction"`
	PremiumExpiresAt *time.Time `json:"premium_expires_at,omitempty" db:"premium_expires_at"`
	CreatedAt        time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at" db:"updated_at"`
}

type PlayerDailyBattle struct {
	PlayerID         string     `json:"player_id" db:"player_id"`
	DailyBattleCount int64      `json:"daily_battle_count" db:"daily_battle_count"`
	LastResetDate    civil.Date `json:"last_reset_date" db:"last_reset_date"`
}
