#!/usr/bin/env python3
"""Generate Go types, WS constants, and TS WS constants from YAML definitions.

Gateway-owned outputs:
  Go:
    - packages/api-gateway/{deck,rest_api,ws_messages,battle_gateway_rpc}_gen.go
    - packages/ws-constants/constants_gen.go
  TS:
    - packages/ws-constants-npm/src/index.ts

Docs:
  - docs/WS_REFERENCE.md (marker-based field table replacement)
  - docs/API_REFERENCE.md (generated from data/endpoints.yaml)

Usage:
    python3 scripts/generate_types.py
"""

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# ─── Paths ──────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

GATEWAY_WS_YAML = DATA_DIR / "ws_constants.yaml"
MODELS_YAML = DATA_DIR / "models.yaml"
ENDPOINTS_YAML = DATA_DIR / "endpoints.yaml"

PACKAGES_DIR = ROOT / "packages"
DOCS_DIR = ROOT / "docs"

# Go module directories.
GO_WS_DIR = PACKAGES_DIR / "ws-constants"
GO_API_GATEWAY_DIR = PACKAGES_DIR / "api-gateway"

# npm package directories.
NPM_WS_DIR = PACKAGES_DIR / "ws-constants-npm"

# Mapping of models.yaml section name → (target Go module dir, Go package name).
# Sections not listed here (e.g., game_state_view with go_skip) are not emitted.
_GO_MODELS_ROUTING = {
    "deck":               (GO_API_GATEWAY_DIR, "apigateway"),
    "rest_api":           (GO_API_GATEWAY_DIR, "apigateway"),
    "ws_messages":        (GO_API_GATEWAY_DIR, "apigateway"),
    "battle_gateway_rpc": (GO_API_GATEWAY_DIR, "apigateway"),
}


# ─── Helpers ────────────────────────────────────────────

_GENERATED_HEADER = "// Code generated by scripts/generate_types.py; DO NOT EDIT."


def _to_pascal(value):
    """Convert a YAML value to a PascalCase identifier."""
    value = value.replace("/", "")
    if "_" in value or "-" in value:
        return "".join(w.title() for w in value.replace("-", "_").split("_"))
    if value and value[0].isupper():
        return value
    return value.title() if value else value


def _go_header(package):
    return [
        _GENERATED_HEADER,
        "",
        f"package {package}",
        "",
    ]


def _write_file(out_path, lines):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


def _ts_header():
    return [
        _GENERATED_HEADER,
        "",
    ]


# ─── Go: ws-constants module ─────────────────────────────
def generate_go_ws(data):
    lines = _go_header("ws")
    ws = data["ws_message_types"]

    lines.append("// WS server message types.")
    lines.append("const (")
    for v in ws["server"]:
        lines.append(f'\tWSServerMsg{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")

    lines.append("// WS client message types.")
    lines.append("const (")
    for v in ws["client"]:
        lines.append(f'\tWSClientMsg{_to_pascal(v)} = "{v}"')
    lines.append(")")
    lines.append("")

    _write_file(GO_WS_DIR / "constants_gen.go", lines)


# ─── Go: model file generation ───────────────────────────
def _go_type_needs_import(type_str):
    imports = set()
    if "time.Time" in type_str or "time." in type_str:
        imports.add("time")
    if "json.RawMessage" in type_str:
        imports.add("encoding/json")
    if "civil.Date" in type_str or "civil." in type_str:
        imports.add("cloud.google.com/go/civil")
    return imports


def _generate_go_model_file(file_def, *, out_path, package_name):
    """Generate a single *_gen.go file from a file definition."""
    lines = [
        _GENERATED_HEADER,
        "",
        f"package {package_name}",
        "",
    ]

    declared_imports = set(file_def.get("imports", []))
    for td in file_def.get("types", []):
        for field in td.get("fields", []):
            declared_imports |= _go_type_needs_import(str(field["type"]))

    if declared_imports:
        std_imports = sorted(i for i in declared_imports if "." not in i.split("/")[0])
        ext_imports = sorted(i for i in declared_imports if "." in i.split("/")[0])
        lines.append("import (")
        for imp in std_imports:
            lines.append(f'\t"{imp}"')
        if std_imports and ext_imports:
            lines.append("")
        for imp in ext_imports:
            lines.append(f'\t"{imp}"')
        lines.append(")")
        lines.append("")

    for ta in file_def.get("type_aliases", []):
        lines.append(f"type {ta['name']} {ta['base']}")
    if file_def.get("type_aliases"):
        lines.append("")

    for cgroup in file_def.get("constants", []):
        ctype = cgroup["type"]
        lines.append("const (")
        for cv in cgroup["values"]:
            lines.append(f'\t{cv["name"]} {ctype} = "{cv["value"]}"')
        lines.append(")")
        lines.append("")

    for td in file_def.get("types", []):
        if td.get("comment"):
            lines.append(f"// {td['comment']}")
        lines.append(f"type {td['name']} struct {{")

        fields = td.get("fields", [])
        if fields:
            max_name_len = max(len(f["name"]) for f in fields)
            max_type_len = max(len(str(f["type"])) for f in fields)

        for field in fields:
            fname = field["name"]
            ftype = str(field["type"])
            tags = []
            if "json" in field:
                tags.append(f'json:"{field["json"]}"')
            if "db" in field:
                tags.append(f'db:"{field["db"]}"')
            tag_str = " ".join(tags)

            name_pad = " " * (max_name_len - len(fname) + 1)
            type_pad = " " * (max_type_len - len(ftype) + 1)

            if tag_str:
                line = f"\t{fname}{name_pad}{ftype}{type_pad}`{tag_str}`"
            else:
                line = f"\t{fname}{name_pad}{ftype}"

            if field.get("comment"):
                line += f" // {field['comment']}"
            lines.append(line)

        lines.append("}")
        lines.append("")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


def generate_go_models():
    """Generate *_gen.go model files from models.yaml.

    Each models.yaml section is routed to a target Go module based on
    _GO_MODELS_ROUTING. Sections not in the routing table (or with
    go_skip: true) are not emitted as Go code.

    Returns a dict of {module_dir: [emitted_section_names]} for logging.
    """
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    emitted = {}

    for file_def in data["files"]:
        file_target = file_def.get("target", "both")
        if file_target != "both" and file_target != "gateway":
            continue
        if file_def.get("go_skip"):
            continue

        name = file_def["name"]
        route = _GO_MODELS_ROUTING.get(name)
        if route is None:
            continue

        module_dir, package_name = route
        out_path = module_dir / f"{name}_gen.go"
        _generate_go_model_file(file_def, out_path=out_path, package_name=package_name)
        emitted.setdefault(module_dir, []).append(name)

    return emitted


# ─── TS: ws-constants-npm ─────────────────────────────────
def generate_ts_ws(data):
    lines = _ts_header()
    ws_types = data["ws_message_types"]
    lines.append(f"export const WS_SERVER_MSG_TYPES = {json.dumps(ws_types['server'])} as const;")
    lines.append("export type WSServerMsgType = (typeof WS_SERVER_MSG_TYPES)[number];")
    lines.append("")
    lines.append(f"export const WS_CLIENT_MSG_TYPES = {json.dumps(ws_types['client'])} as const;")
    lines.append("export type WSClientMsgType = (typeof WS_CLIENT_MSG_TYPES)[number];")
    lines.append("")
    _write_file(NPM_WS_DIR / "src" / "index.ts", lines)


# ─── Update WS reference docs (marker-based) ─────────────
_DOC_TYPE_MAP = {
    "string": "string",
    "int": "number",
    "int64": "number",
    "bool": "boolean",
    "time.Time": "string (ISO 8601)",
    "json.RawMessage": "object",
    "interface{}": "unknown",
    "map[string]interface{}": "object",
}


def _json_placeholder(go_type):
    """Return a JSON placeholder value string for a Go type."""
    _placeholders = {
        "string": '"string"',
        "int": "0",
        "int64": "0",
        "bool": "false",
        "time.Time": '"2006-01-02T15:04:05Z"',
        "json.RawMessage": "{}",
        "interface{}": "null",
        "map[string]interface{}": "{}",
    }
    is_pointer = go_type.startswith("*")
    base = go_type.lstrip("*")
    if base.startswith("[]"):
        return "[]"
    if base.startswith("map["):
        return "{}"
    if is_pointer:
        return "null"
    return _placeholders.get(base, '"{}"'.format(base))


def _generate_field_table(type_def):
    """Generate a Markdown field table + JSON skeleton for a type definition."""
    doc_fields = []
    for field in type_def.get("fields", []):
        if "doc" not in field:
            continue
        json_tag = field["json"]
        json_key = json_tag.split(",")[0]
        go_type = str(field["type"])
        doc_fields.append((json_key, go_type, field["doc"]))

    if not doc_fields:
        return None

    json_entries = []
    for json_key, go_type, doc in doc_fields:
        json_entries.append(f'  "{json_key}": {_json_placeholder(go_type)} // {doc}')
    json_body = ",\n".join(json_entries)
    return f"```jsonc\n{{\n{json_body}\n}}\n```"


def update_doc_field_tables(doc_path):
    """Replace marker-delimited sections in a Markdown file with generated field tables."""
    doc_file = Path(doc_path)
    if not doc_file.exists():
        return False

    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    type_map = {}
    for file_def in data.get("files", []):
        for td in file_def.get("types", []):
            type_map[td["name"]] = td

    with open(doc_file, "r", encoding="utf-8") as f:
        content = f.read()

    marker_re = re.compile(
        r"(<!-- BEGIN GENERATED: (\w+) -->)\n(.*?)(<!-- END GENERATED: \2 -->)",
        re.DOTALL,
    )

    def replacer(match):
        begin_tag = match.group(1)
        type_name = match.group(2)
        end_tag = match.group(4)
        td = type_map.get(type_name)
        if td is None:
            print(f"WARNING: type '{type_name}' not found in models.yaml, skipping marker in {doc_file.name}", file=sys.stderr)
            return match.group(0)
        table = _generate_field_table(td)
        if table is None:
            return match.group(0)
        return f"{begin_tag}\n{table}\n{end_tag}"

    new_content = marker_re.sub(replacer, content)
    if new_content == content:
        return False

    with open(doc_file, "w", encoding="utf-8") as f:
        f.write(new_content)
    return True


# ─── API Reference generation ─────────────────────────

def _doc_type(go_type):
    """Convert a Go type string to a human-readable doc type."""
    is_pointer = go_type.startswith("*")
    base = go_type.lstrip("*")

    if base.startswith("[]*"):
        elem = base[3:]
        return f"({_DOC_TYPE_MAP.get(elem, elem)} | null)[]"
    if base.startswith("[]"):
        elem = base[2:]
        return f"{_DOC_TYPE_MAP.get(elem, elem)}[]"

    doc_base = _DOC_TYPE_MAP.get(base, base)
    if is_pointer:
        return f"{doc_base}?"
    return doc_base


def _find_type_def(data: dict, type_name: str) -> dict | None:
    """Find a type definition by name across all files in models.yaml."""
    for file_def in data.get("files", []):
        for td in file_def.get("types", []):
            if td["name"] == type_name:
                return td
    return None


def _render_type_table(lines: list[str], data: dict, type_name: str) -> None:
    """Render a field table for the given type name."""
    td = _find_type_def(data, type_name)
    if td is None:
        lines.append(f"*型 `{type_name}` は models.yaml に未定義*\n")
        return
    fields = td.get("fields", [])
    if not fields:
        lines.append("*フィールドなし*\n")
        return
    lines.append("| フィールド | 型 | JSON | 説明 |")
    lines.append("|---|---|---|---|")
    for field in fields:
        json_key = field.get("json", "").split(",")[0]
        go_type = str(field.get("type", ""))
        doc = field.get("doc", "")
        lines.append(f"| {field['name']} | `{_doc_type(go_type)}` | `{json_key}` | {doc} |")
    lines.append("")


def generate_api_reference(ep_data: dict, models_data: dict, output_path: Path) -> None:
    """Generate docs/API_REFERENCE.md from endpoints.yaml endpoint_groups + messages."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# API リファレンス",
        "",
        "> 自動生成 -- 直接編集しない。`data/endpoints.yaml` の `endpoint_groups` セクションから",
        "> `python3 scripts/generate_types.py` で生成される。",
        "",
        f"生成日時: `{now}`",
        "",
    ]

    for group in ep_data.get("endpoint_groups", []):
        lines.append(f"## {group['name']}")
        lines.append("")
        if group.get("description"):
            for dl in group["description"].strip().splitlines():
                lines.append(dl)
            lines.append("")
        if group.get("auth"):
            lines.append(f"**認証**: `{group['auth']}`")
            lines.append("")
        if group.get("base_path"):
            lines.append(f"**ベースパス**: `{group['base_path']}`")
            lines.append("")
        if group.get("path"):
            lines.append(f"**パス**: `{group['path']}`")
            lines.append("")

        # REST endpoints
        for ep in group.get("endpoints", []):
            lines.append(f"### `{ep['method']} {ep['path']}`")
            lines.append("")
            lines.append(ep["summary"])
            lines.append("")

            if ep.get("request_type"):
                lines.append(f"**リクエスト**: `{ep['request_type']}`")
                lines.append("")
                _render_type_table(lines, models_data, ep["request_type"])

            if ep.get("response_type"):
                resp_desc = ep.get("response_description", "")
                if resp_desc:
                    lines.append(f"**レスポンス**: {resp_desc}")
                else:
                    lines.append(f"**レスポンス**: `{ep['response_type']}`")
                lines.append("")
                _render_type_table(lines, models_data, ep["response_type"])

            elif ep.get("response_description"):
                lines.append(f"**レスポンス**: {ep['response_description']}")
                lines.append("")

            if ep.get("response_status") and not ep.get("response_type"):
                desc = ep.get("response_description", "")
                lines.append(f"**成功レスポンス**: `{ep['response_status']}` {desc}")
                lines.append("")

            if ep.get("errors"):
                lines.append("**エラー**:")
                lines.append("")
                lines.append("| ステータス | 説明 |")
                lines.append("|---|---|")
                for err in ep["errors"]:
                    lines.append(f"| `{err['status']}` | {err['description']} |")
                lines.append("")

            if ep.get("notes"):
                for note_line in ep["notes"].strip().splitlines():
                    lines.append(f"> {note_line}")
                lines.append("")

        # WS messages
        messages = group.get("messages", {})
        if messages:
            c2s = messages.get("client_to_server", [])
            s2c = messages.get("server_to_client", [])

            if c2s:
                lines.append("### Client -> Server メッセージ")
                lines.append("")
                lines.append("| メッセージタイプ | ペイロード型 | 説明 |")
                lines.append("|---|---|---|")
                for msg in c2s:
                    pt = f"`{msg['payload_type']}`" if msg.get("payload_type") else "--"
                    lines.append(f"| `{msg['type']}` | {pt} | {msg['summary']} |")
                lines.append("")

                for msg in c2s:
                    if msg.get("payload_type"):
                        lines.append(f"#### `{msg['type']}`")
                        lines.append("")
                        lines.append(msg["summary"])
                        lines.append("")
                        lines.append(f"**ペイロード**: `{msg['payload_type']}`")
                        lines.append("")
                        _render_type_table(lines, models_data, msg["payload_type"])

            if s2c:
                lines.append("### Server -> Client メッセージ")
                lines.append("")
                lines.append("| メッセージタイプ | ペイロード型 | 説明 |")
                lines.append("|---|---|---|")
                for msg in s2c:
                    pt = f"`{msg['payload_type']}`" if msg.get("payload_type") else "--"
                    lines.append(f"| `{msg['type']}` | {pt} | {msg['summary']} |")
                lines.append("")

                for msg in s2c:
                    if msg.get("payload_type"):
                        lines.append(f"#### `{msg['type']}`")
                        lines.append("")
                        lines.append(msg["summary"])
                        lines.append("")
                        lines.append(f"**ペイロード**: `{msg['payload_type']}`")
                        lines.append("")
                        _render_type_table(lines, models_data, msg["payload_type"])

        lines.append("---")
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


# ─── Main ──────────────────────────────────────────────
def _load_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def main():
    # Load YAML sources.
    gateway_ws = _load_yaml(GATEWAY_WS_YAML)
    models = _load_yaml(MODELS_YAML)

    # ── Go: ws-constants ──
    generate_go_ws(gateway_ws)
    print("Generated → packages/ws-constants/constants_gen.go", file=sys.stderr)

    # ── Go: api-gateway models ──
    emitted = generate_go_models()
    for module_dir, names in emitted.items():
        rel = module_dir.relative_to(ROOT)
        print(f"Generated models → {rel}/ [{', '.join(names)}]", file=sys.stderr)

    # ── TS: ws-constants-npm ──
    generate_ts_ws(gateway_ws)
    print("Generated → packages/ws-constants-npm/src/index.ts", file=sys.stderr)

    # ── Docs (marker-based field table replacement) ──
    if update_doc_field_tables(DOCS_DIR / "WS_REFERENCE.md"):
        print("Updated field tables → docs/WS_REFERENCE.md", file=sys.stderr)

    # ── API Reference (from endpoints.yaml) ──
    if ENDPOINTS_YAML.exists():
        ep_data = _load_yaml(ENDPOINTS_YAML)
        api_ref_path = ROOT / "docs" / "API_REFERENCE.md"
        generate_api_reference(ep_data, models, api_ref_path)
        print("Generated → docs/API_REFERENCE.md", file=sys.stderr)


if __name__ == "__main__":
    main()
