// Code generated by generate_from_yaml.py from data/constants.json; DO NOT EDIT.

package constants

// Deck size.
const (
	DeckSize = 30
)

// Faction constants.
const (
	FactionSD = "SD"
	FactionTenki = "Tenki"
	FactionSugar = "Sugar"
	FactionTuners = "Tuners"
	FactionNeutral = "Neutral"
)
